# Generated by Django 4.1.1 on 2022-09-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourses', '0005_tags_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='cares',
            field=models.ManyToManyField(blank=True, null=True, related_name='lessons', to='ecourses.cares'),
        ),
    ]
